from pyscript import display, document

def Players(e):
    document.getElementById("output").innerHTML = ""
    names = [ '1) ASEO, TESSA YSABELLE MARZAN', '2) BATAC, ANAKIN MIGUEL QUINTO', '3) CALANGLANG, NERIZA ALIPIO', '4) DE GUZMAN, VITO ANTONIO OLIVERA', '5) DEE, AARON JAMES GONZALO', '6) DOLOR, HARVEY WAYNE BATINO', '7) GALVEZ, SELENA MANSUETO', '8) GARCES, ADRIANNA MALANUM', '9) GROSPE, JILLIAN CUISON', '10) HIZON, EDUARDO ALONSO MAGSOMBOL', '11) INTALAN, MARGO ZERA FRANCISCO', '12) KO, ATASHA SOLEIL ROMERO', '13) LAGMAN, ALIJAH RAIN', '14) MEDINA, KELSEY CLAIRE LAGO', '15) LAW, MARCUS CHRISTIAN PANLILIO', '16) MACABAGO, SITTIE AINAH MARIANO', '17) MARTINEZ, EUAN JUSTIN LIM', '18) MENDOZA, MICHAELA YSABELLE CAYNO', '19) MERGAL, MANUEL JACINTO GUARINO', '20) NGO, SETH GARETT GOMEZ', '21) PADOJINOG, SOFIA LAURENCE FABELLA', '22) RIVERA, BENIGNO IGNACIO JHOCSON', '23) SHRESTHA, ISHAN JUSTICE QUIAMBAO', '24) UY, JENNIFER LORRAINE SANCHEZ', '25) YAO, FRANCESCA JEAN KHO']							

    for name in names:

        display(name, target='output')
